runtime: python38
instance_class: F4_1G
entrypoint: gunicorn -b :$PORT appengine:app --timeout 3600
automatic_scaling:
    min_instances: 1
    max_instances: 1000
    max_concurrent_requests: 1
    target_cpu_utilization: 0.65
