name: Run Data Pipeline
# Run the data pipeline twice a day, at 12:00 and 20:00 UTC

on:
  schedule:
    - cron: "0 12,20 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Fetch current data
      working-directory: src
      run: |
        python ./run.py --verify
        git add -f output
        git config user.name open-covid-bot
        git config user.email open-covid-bot@${{ github.repository }}
        git commit -m "Automatic data fetch"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        branch-name: data-update
        branch-suffix: timestamp
